import { ColorPreset, StylePreset, HalftoneSettings } from '../types/halftone';

export const DEFAULT_SETTINGS: HalftoneSettings = {
  enableHalftone: true,
  lpi: 30, // 30 LPI Standard
  angle: 22.5,
  pattern: 'circle',
  dotScale: 1.0,

  shirtColor: '#050505',
  shirtColorPreview: true,
  knockoutShirtColor: true, // Eliminates black box background!
  knockoutThreshold: 18,
  edgeChoke: 1, // Eliminates white halo/haze

  bgRemoval: {
    enabled: true,
    targetColor: '#000000',
    tolerance: 20,
    feather: 2,
    edgeChoke: 0,
    despeckle: false,
    autoDetectBlack: true,
  },

  levels: {
    shadow: 10,
    midtones: 1.0,
    highlight: 250,
  },

  colorAdjust: {
    hue: 0,
    saturation: 0,
    lightness: 0,
    contrast: 1.0,
  },

  whiteBase: {
    enabled: true,
    choke: 1,
    minDensity: 5,
  },

  // DEFAULT: Retém as cores originais da arte!
  inkMode: 'original-colors',
  inkColor: '#00E5FF',
};

export const COLOR_PRESETS: ColorPreset[] = [
  {
    id: 'original-colors',
    name: 'Cores Originais da Arte',
    category: 'original',
    hex: 'multi',
    description: 'Mantém 100% as cores originais e gradientes da sua imagem na retícula',
    badge: 'Padrão',
  },
  {
    id: 'pink-neon',
    name: 'Rosa Neon',
    category: 'neon',
    hex: '#EC4899',
    description: 'Magenta fluorescente de alto impacto e brilho',
    badge: 'Neon',
  },
  {
    id: 'cyan-neon',
    name: 'Azul Ciano Neon',
    category: 'neon',
    hex: '#00E5FF',
    description: 'Ciano elétrico puro para máxima visibilidade e contraste',
    badge: 'Neon',
  },
  {
    id: 'green-neon',
    name: 'Verde Ácido Neon',
    category: 'neon',
    hex: '#10B981',
    description: 'Verde fluorescente cibernético de alta definição',
    badge: 'Neon',
  },
  {
    id: 'purple-neon',
    name: 'Roxo Elétrico',
    category: 'neon',
    hex: '#A855F7',
    description: 'Violeta neon cósmico moderno',
    badge: 'Neon',
  },
  {
    id: 'gold-vintage',
    name: 'Ouro Vintage',
    category: 'classico',
    hex: '#D4A359',
    description: 'Tom dourado nobre envelhecido para estampas clássicas',
    badge: 'Ouro',
  },
  {
    id: 'white-dtf',
    name: 'Branco Puro DTF',
    category: 'mono',
    hex: '#FFFFFF',
    description: 'Branco opaco absoluto para impressão em camisetas pretas',
    badge: 'Branco',
  },
  {
    id: 'black-ink',
    name: 'Preto Tinta',
    category: 'mono',
    hex: '#050505',
    description: 'Preto profundo para impressão em fundos claros ou fotolito',
    badge: 'Preto',
  },
  {
    id: 'yellow-chrome',
    name: 'Amarelo Cromo',
    category: 'neon',
    hex: '#FACC15',
    description: 'Amarelo canário brilhante de sinalização',
    badge: 'Neon',
  },
];

export const STYLE_PRESETS: StylePreset[] = [
  {
    id: 'dtf-standard-30lpi',
    name: 'DTF Padrão 30 LPI (Cores da Arte)',
    description: 'Elimina fundo preto e névoa branca mantendo as cores reais da arte com pontos de 30 LPI',
    category: 'DTF / DTG',
    settings: {
      enableHalftone: true,
      lpi: 30,
      angle: 22.5,
      pattern: 'circle',
      shirtColor: '#050505',
      shirtColorPreview: true,
      knockoutShirtColor: true,
      knockoutThreshold: 18,
      edgeChoke: 1,
      inkMode: 'original-colors',
      levels: { shadow: 10, midtones: 1.0, highlight: 250 },
    },
  },
  {
    id: 'dtf-fine-45lpi',
    name: 'DTF Fine Art 45 LPI (Alta Resolução)',
    description: 'Retícula fina de 45 LPI para gradientes contínuos e fotorealistas',
    category: 'DTF / DTG',
    settings: {
      enableHalftone: true,
      lpi: 45,
      angle: 22.5,
      pattern: 'circle',
      shirtColor: '#050505',
      shirtColorPreview: true,
      knockoutShirtColor: true,
      knockoutThreshold: 16,
      edgeChoke: 1,
      inkMode: 'original-colors',
      levels: { shadow: 8, midtones: 1.05, highlight: 245 },
    },
  },
  {
    id: 'dtf-smooth-diamond',
    name: 'DTG Transição Suave (Losangos)',
    description: 'Pontos em losango a 45° para fusão imperceptível com a textura da camisa',
    category: 'DTF / DTG',
    settings: {
      enableHalftone: true,
      lpi: 25,
      angle: 45,
      pattern: 'diamond',
      shirtColor: '#080808',
      shirtColorPreview: true,
      knockoutShirtColor: true,
      knockoutThreshold: 20,
      edgeChoke: 1,
      inkMode: 'original-colors',
    },
  },
  {
    id: 'spot-gold-screen',
    name: 'Monocromático Ouro Vintage',
    description: 'Separação em tinta dourada única com fundo preto 100% eliminado',
    category: 'Serigrafia',
    settings: {
      enableHalftone: true,
      lpi: 30,
      angle: 45,
      pattern: 'circle',
      shirtColor: '#050505',
      knockoutShirtColor: true,
      knockoutThreshold: 20,
      edgeChoke: 1,
      inkMode: 'spot',
      inkColor: '#D4A359',
    },
  },
  {
    id: 'spot-white-dtf',
    name: 'Monocromático Branco Puro',
    description: 'Separação em tinta branca com transparência total para tecidos escuros',
    category: 'DTF',
    settings: {
      enableHalftone: true,
      lpi: 30,
      angle: 22.5,
      pattern: 'circle',
      shirtColor: '#050505',
      knockoutShirtColor: true,
      knockoutThreshold: 20,
      edgeChoke: 1,
      inkMode: 'spot',
      inkColor: '#FFFFFF',
    },
  },
  {
    id: 'black-film-darkroom',
    name: 'Fotolito Preto (Telas Serigráficas)',
    description: 'Preto puro absoluto sobre transparente com contraste extremo para matrizes',
    category: 'Gráfica',
    settings: {
      enableHalftone: true,
      lpi: 35,
      angle: 45,
      pattern: 'circle',
      shirtColor: '#FFFFFF',
      knockoutShirtColor: false,
      edgeChoke: 0,
      inkMode: 'spot',
      inkColor: '#050505',
      levels: { shadow: 25, midtones: 0.9, highlight: 235 },
    },
  },
];
